name: iirjdart
description: >-
  An IIR filter library written in Dart.
  Highpass, lowpass, bandpass and bandstop as Butterworth, Bessel and Chebyshev Type I/II.
version: 0.1.0
homepage: https://github.com/Supercaly/iirj_dart
repository: https://github.com/Supercaly/iirj_dart
issue_tracker: https://github.com/Supercaly/iirj_dart/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  complex: ^0.7.2

dev_dependencies:
  test: ^1.21.7

